// <auto-generated />
using System;
using Bolao.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bolao.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702215441_MenuHeader")]
    partial class MenuHeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bolao.Domain.Aggregates.Championship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Championships", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupStageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupStageId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.GroupStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GroupStages");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.MenuHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Href");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("MenuHeader", (string)null);
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Stadium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearFounded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Match", b =>
                {
                    b.OwnsOne("Bolao.Domain.Entities.MatchResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");

                            b1.OwnsOne("Bolao.Domain.ValueObjects.GoalCount", "AwayGoals", b2 =>
                                {
                                    b2.Property<Guid>("MatchResultMatchId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("AwayGoals");

                                    b2.HasKey("MatchResultMatchId");

                                    b2.ToTable("Matches");

                                    b2.WithOwner()
                                        .HasForeignKey("MatchResultMatchId");
                                });

                            b1.OwnsOne("Bolao.Domain.ValueObjects.GoalCount", "HomeGoals", b2 =>
                                {
                                    b2.Property<Guid>("MatchResultMatchId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("HomeGoals");

                                    b2.HasKey("MatchResultMatchId");

                                    b2.ToTable("Matches");

                                    b2.WithOwner()
                                        .HasForeignKey("MatchResultMatchId");
                                });

                            b1.Navigation("AwayGoals")
                                .IsRequired();

                            b1.Navigation("HomeGoals")
                                .IsRequired();
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Prediction", b =>
                {
                    b.OwnsOne("Bolao.Domain.ValueObjects.Points", "CalculatedPoints", b1 =>
                        {
                            b1.Property<Guid>("PredictionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("CalculatedPoints");

                            b1.HasKey("PredictionId");

                            b1.ToTable("Predictions");

                            b1.WithOwner()
                                .HasForeignKey("PredictionId");
                        });

                    b.OwnsOne("Bolao.Domain.ValueObjects.GoalCount", "PredictedAwayGoals", b1 =>
                        {
                            b1.Property<Guid>("PredictionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("PredictedAwayGoals");

                            b1.HasKey("PredictionId");

                            b1.ToTable("Predictions");

                            b1.WithOwner()
                                .HasForeignKey("PredictionId");
                        });

                    b.OwnsOne("Bolao.Domain.ValueObjects.GoalCount", "PredictedHomeGoals", b1 =>
                        {
                            b1.Property<Guid>("PredictionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("PredictedHomeGoals");

                            b1.HasKey("PredictionId");

                            b1.ToTable("Predictions");

                            b1.WithOwner()
                                .HasForeignKey("PredictionId");
                        });

                    b.Navigation("CalculatedPoints");

                    b.Navigation("PredictedAwayGoals")
                        .IsRequired();

                    b.Navigation("PredictedHomeGoals")
                        .IsRequired();
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.User", b =>
                {
                    b.OwnsOne("Bolao.Domain.ValueObjects.Points", "TotalScore", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("TotalScore");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("TotalScore")
                        .IsRequired();
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Group", b =>
                {
                    b.HasOne("Bolao.Domain.Entities.GroupStage", null)
                        .WithMany("Groups")
                        .HasForeignKey("GroupStageId");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.Player", b =>
                {
                    b.HasOne("Bolao.Domain.Aggregates.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bolao.Domain.Aggregates.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Bolao.Domain.Entities.GroupStage", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
